# Generated by Django 5.1.2 on 2025-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='intereses',
            field=models.ManyToManyField(related_name='Usuarios', through='api.InteresesUsuarios', to='api.intereses'),
        ),
    ]
